spring.application.name=task-scheduler
server.port=8080
management.endpoints.web.exposure.include=health,info
spring.datasource.url=jdbc:postgresql://localhost:5432/task_scheduler_db
spring.datasource.username=postgres
spring.datasource.password=kushagra123
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=60000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true